### ISSUE TITLE
Needs Documentation

### ISSUE THREAD

**Issue by dwb357** [mfuchs/android-emulators-gradle#2]
This looks like a good start, but it desperately needs documentation.

**Comment by mfuchs** [comment]
Thanks for your input! Can you give me some hints of what information you are missing?

**Comment by dwb357** [comment]
Given that there’s absolutely no documentation here, and that all that on gradle.org is how to `apply` it, I’m going to have to with “all of it.”

Most specifically, there’s no discussion of where it should be applied (seems like it needs to be applied to any android targets, but that’s a guess) or how to configure it, although it seems configuration is required.

**Comment by mfuchs** [comment]
Ah sorry! I did not realise that you are on the repo of my account.
I moved the code to https://github.com/Catrobat/Gradle
There is also some basic documentation.

Sorry for the misunderstanding. I guess I'll remove this repo.
