### ISSUE TITLE
Allow ANDROID_AVD_HOME set up.

### ISSUE THREAD

**Issue by dwb357** [mfuchs/android-emulators-gradle#3]
Currently if this is undefined your avds and a bunch of other files get dumped in the root directory of your project.  It would be much friendlier to source control and continuous integration systems if some changes were made to that:

* default to somewhere in the build directory
* allow configuration as part of the emulators block

**Comment by mfuchs** [comment]
Good idea! I'll look into it and will implement it at https://github.com/Catrobat/Gradle

**Comment by mfuchs** [comment]
I'll implemented this with v1.6.0 at https://github.com/Catrobat/Gradle
